export const ActionTypes={
    FETCH_DATA:'FETCH_DATA',
    CHECK_ANSWER:'CHECK_ANSWER',
    COUNTER:'COUNTER',
    FETCH_TEN_ITEMS:'FETCH_TEN_ITEMS',
    RESET_CORRECT:'RESET_CORRECT',
    RESET_COUNTER:'RESET_COUNTER'
};